# Generated by Django 4.0.5 on 2022-07-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('cx_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=40)),
                ('disposition1', models.CharField(max_length=50)),
                ('disposition2', models.CharField(max_length=50)),
            ],
        ),
    ]
