# Generated by Django 4.0.5 on 2022-07-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetail',
            new_name='VikasCustomerDetail',
        ),
    ]
